### ISSUE TITLE
Several people can do at the same time.

### ISSUE THREAD

**Issue by Sprayers** [apoiat/esx_cargodelivery#1]
Hi, as i tested it today with my friends, i noticed that only 1 of us was able to take the cargo mission. Is it possible to make it so that several people can take missions at the same time? Im not sure if this is a bug or it is supposed to be like that. Would be cool if more than 1 can take the mission.

**Comment by apoiat** [comment]
Hello, it was designed like this initially so i will have to take this into consideration as an enhancement. Thanks for your suggestion
